project_name: gh-manager
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download

builds:
  - binary: gh-manager
    id: gh-manager
    ldflags:
      - -X github.com/flemzord/gh-manager/cmd.BuildDate={{ .Date }}
      - -X github.com/flemzord/gh-manager/cmd.Version={{ .Version }}
      - -X github.com/flemzord/gh-manager/cmd.Commit={{ .ShortCommit }}
      - -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: "gh-manager"
    builds:
      - gh-manager
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Os}}-{{.Arch}}"


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^spec:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/flemzord/gh-manager/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - tap:
      owner: flemzord
      name: homebrew-tap
    name: gh-manager
    folder: Formula
    homepage: https://maxence.maireaux.fr
    skip_upload: 'false'
    test: |
      system "#{bin}/gh-manager version"
    install: |
      bin.install "gh-manager"