dryrun: true
github:
  organization: YOUR ORGANIZATION
  token: YOUR TOKEN

repository:
  permissions:
    - team: Admin
      permission: admin
    - team: DevOps
      permission: maintain
    - team: Dev
      permission: maintain
  ignore:
    team:
      - Exclude